name: "refresh github_activity function"

on:
  schedule:
    - cron:  '15 3 * * *'

  push:
   branches:
     - main

env:
  STEAMPIPE_CLOUD_TOKEN: ${{ secrets.STEAMPIPE_CLOUD_TOKEN }}

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: push the function
      run: python push-function.py

    - name: exit
      if: ${{ steps.checks.outcome == 'failure' }}
      run: exit 1
      
